language: python
matrix:
  include:
    - python: "2.7"
    - pytest

virtualenv:
  system_site_packages: true

before_script:
  - pip install --upgrade git+git://github.com/SpiNNakerManchester/SpiNNMachine.git@master
  - pip install -r requirements-test.txt
  - python ./setup.py install
script:
  - py.test unittests
  - py.test integration_tests
  # Code quality check
  - flake8 pacman
  - flake8 integration_tests unittests uinit_test_objects
